module.exports = {
    name: "dare",
    alias: ["givedare","d"],
    desc: "trau dich",
    cool:3,
    react: "🙄",
    category: "Fun",
    start: async(Miku, m,{text, prefix}) => {

     
      
    const shibam = ["Essen Sie 2 Esslöffel Reis ohne Beilagen, wenn es schleppend ist, können Sie trinken",
         "verschütte Leute, die dich innehalten lassen",
         "Jetzt Crush/Pickle anrufen und ss senden",
         "Drop-Only-Emote jedes Mal, wenn Sie 1 Tag lang auf gc/pc tippen.",
         "Sagen Sie Willkommen zu Wer wird Millionär! an alle Gruppen, die Sie haben",
         "Ex anrufen und vermissen sagen",
         "Singen Sie den Refrain des letzten Liedes, das Sie gespielt haben",
         "vn dein/e Ex/Crush/Freundin, sagt hallo (Name), will anrufen, einen Moment. ich vermisse🥺👉🏼👈🏼",
         "Schlagen Sie auf den Tisch (der zu Hause ist), bis Sie wegen Lärms gescholten werden",
         "Sagen Sie es zufälligen Leuten – mir wurde gerade gesagt, dass ich zuerst Ihr Zwilling war, wir haben uns getrennt, dann hatte ich eine Schönheitsoperation. Und das ist das ciyusss_-Ding",
         "Erwähne den Namen des Ex",
         "Machen Sie 1 Reim für die Mitglieder!",
         "Sende deine WhatsApp-Chatliste",
         "Chatte zufällige Leute mit Gheto-Sprache, dann ss hier",
         "erzähle deine eigene Version von peinlichen Dingen",
         "Markiere die Person, die du hasst“,
         "Besessenheit vortäuschen, zum Beispiel: von einem Hund besessen, von Heuschrecken besessen, von einem Kühlschrank besessen usw.",
         "Ändere den Namen für 24 Stunden in *I AM DONKEY*",
         "ruf *ma chuda ma chuda ma chuda* vor deinem Haus",
         "Freundfoto schnappen/posten/verknallt",
         "Sag mir deinen Freundtyp!",
         "Sag * ich bin in dich verknallt, willst du meine Freundin sein?
         "nimm deine Stimme auf, die *titar ke age do titar, titar ke piche do titar* lautet",
         "Streiche Chat-Ex und sag *ich liebe dich, bitte komm zurück.*, ohne zu sagen, trau dich!",
         "chatten Sie, um wa in der Reihenfolge Ihrer Batterie % zu kontaktieren, und sagen Sie ihm dann *ich habe Glück mit Ihnen!*",
         "Ändere den Namen für 5 Stunden in *Ich bin ein Kind von Randi*",
         "geben Sie Bengali 24 Stunden ein",
         "Verwenden Sie Selmon Bhoi Photo für 3 Tage",
         "Schreibe ein Liedzitat und markiere dann ein passendes Mitglied für dieses Zitat",
         "Sende eine Sprachnotiz mit der Aufschrift Kann ich dich anrufen?",
         "ss letzten anruf whatsapp",
         "Sag *DU BIST SO SCHÖN LÜG NICHT* zu Jungs!",
         "Komm zu einem Gruppenmitglied und sag Fick dich",
         "Benimm dich vor deinen Eltern wie ein Huhn",
         "Nehmen Sie ein beliebiges Buch und lesen Sie eine Seite laut in vn n und senden Sie es hierher",
         "Öffnen Sie Ihre Haustür und heulen Sie 10 Sekunden lang wie ein Wolf",
         "Nehmen Sie ein peinliches Selfie und fügen Sie es in Ihr Profilbild ein",
         "Lassen Sie die Gruppe ein Wort und ein bekanntes Lied auswählen. Sie müssen dieses Lied singen und es in einer Sprachnotiz senden",
         "Laufen Sie so lange wie möglich auf Ellbogen und Knien",
         "Nationalhymne in Sprachnotiz singen",
         "30 Sekunden Breakdance im Wohnzimmer😂“,
         "Erzähl die traurigste Geschichte, die du kennst“,
         "Mach ein Twerk-Tanzvideo und setze es für 5 Minuten auf Status“,
         "Iss ein rohes Stück Knoblauch",
         "Zeige die letzten fünf Personen, denen du eine SMS geschrieben hast, und was in den Nachrichten stand",
         "setzen Sie Ihren vollständigen Namen für 5 Stunden in den Status",
         "Machen Sie ein kurzes Tanzvideo ohne Filter nur mit Musik und setzen Sie es für 5 Stunden auf Ihren Status“,
         "Ruf deine beste Freundin an, Schlampe",
         "Stellen Sie Ihr Foto 10 Minuten lang ohne Filter auf Ihren Status",
         "Sag i love oli london in voice note🤣🤣“,
         "Sende eine Nachricht an deinen Ex und sage, dass ich dich immer noch mag“,
         "Crush/Freundin/Bestie jetzt anrufen und Screenshot hier",
         "Schauen Sie zu einem der persönlichen Chats der Gruppenmitglieder und sagen Sie, Sie hässliche Trappe",
         "Sag DU BIST SCHÖN/SCHÖN zu einer Person, die ganz oben auf deiner Pinliste steht, oder der ersten Person auf deiner Chatliste",
         "Sende Sprachnotizen und sag, kann ich dich anrufen, Baby, wenn du ein Junge bist, markiere ein Mädchen/wenn ein Mädchen einen Jungen markiert",
         "schreibe ich liebe dich (zufälliger Gruppenmitgliedsname, der online ist) im persönlichen Chat, (wenn dein Junge einen Mädchennamen schreibt/wenn ein Mädchen einen Jungennamen schreibt) mach ein Foto und sende es hierher",
         "benutze 3 Tage lang ein beliebiges Bollywood-Schauspielerfoto als dein PFP",
         "Setze dein Crush-Foto mit Bildunterschrift auf Status, das ist mein Crush",
         "Ändere den Namen für 5 Stunden in ICH BIN GAY",
         "Chatte mit jedem Kontakt in WhatsApp und sage, dass ich für 5 Stunden dein Freund/Freundin sein werde",
         "Sende Sprachnotiz, dass ich in dich verknallt bin, willst du meine Freundin/mein Freund sein oder nicht? an eine zufällige Person aus der Gruppe (wenn du Mädchen wählst, Junge, wenn Junge Mädchen wählst",
         "Schlag auf deinen Hintern, sende kaum das Geräusch einer Ohrfeige durch die Sprachnotiz😂",
         "Geben Sie Ihre Freundin/Ihren Freund an und senden Sie das Foto hier mit der Bildunterschrift Hässlichstes Mädchen/Junge der Welt",
         "Rufe bravooooooooo und sende hier per Sprachnotiz",
         "Schnips dein Gesicht und schick es dann hierher",
         "Sende dein Foto mit einer Bildunterschrift, ich bin lesbisch",
         "schreien Sie mit harten Worten und senden Sie es hier durch vn",
         "schrei du Bastard vor deiner Mama/ deinem Papa",
         "Ändere den Namen für 24 Stunden in Ich bin Idiot",
         "Schlag dich selbst fest und sende den Klang des Schlags durch die Sprachnotiz😂“,
         "Sag ich liebe den Bot-Besitzer Fantox durch eine Sprachnotiz",
         "schicke hier dein gf/bf bild",
         "Erstellen Sie ein beliebiges Tiktok-Tanz-Challenge-Video und setzen Sie es auf Status, Sie können es nach 5 Stunden löschen",
         "trenne dich für 5 Stunden von deinem besten Freund, ohne ihm/ihr zu sagen, dass es eine Herausforderung ist“,
         "Sag einem deiner Freunde, dass du ihn/sie liebst und ihn/sie heiraten willst, ohne ihm/ihr zu sagen, dass es eine Herausforderung ist“,
         "Sag ich liebe Depak Kalal durch Sprachnotiz",
         "Schreibe, ich fühle mich geil und setze es auf Status, du kannst es erst nach 5 Stunden löschen",
         "Schreibe ich bin lesbisch und setze es auf Status, du kannst es erst nach 5 Stunden löschen",
         "küss deine Mami oder deinen Papa und sag ich liebe dich😌",
         "Setze den Namen deines Vaters für 5 Stunden auf Status",
         "Senden Sie beleidigende Wörter in jeder Gruppe außer dieser Gruppe und senden Sie hier einen Screenshot-Beweis"]
    const dey = shibam[Math.floor(Math.random() * shibam.length)]
   
    
    let buttons = [
      {
        buttonId: `${prefix}t`,
        buttonText: { displayText: "Truth" },
        type: 1,
      },
      {
        buttonId: `${prefix}d`,
        buttonText: { displayText: "Weiter..." },
        type: 1,
      },
    ];
  
let buttonMessage = {
      image: { url:botImage4},
      caption: dey,
      footer: `*${botName}*`,
      buttons: buttons,
      headerType: 4,
    };


     await Miku.sendMessage(m.from,buttonMessage,{quoted:m});
}
}
